[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src self; upgrade-insecure-requests"
    Permissions-Policy = "fullscreen=(self), geolocation=(), camera=(), microphone=()"
    Referrer-Policy = "no-referrer"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
